services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: spotify
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  
  backend:
    build: ./Django
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=spotify
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
    volumes:
      - ./Django:/app

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
  admin:
    build: ./frontend-admin    # Sửa thành đường dẫn chính xác
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules

volumes:
  mysql_data: