# Generated by Django 4.2.19 on 2025-04-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_track_is_premium_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='uri',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='', help_text='File nhạc MP3 hoặc MP4', upload_to='tracks/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa cho bài hát (JPG, PNG)', null=True, upload_to='track_covers/'),
        ),
    ]
