# Generated by Django 4.2.19 on 2025-04-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_track_uri_track_audio_file_track_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.CharField(help_text='S3 key cho file nhạc MP3/MP4', max_length=1024),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.CharField(blank=True, help_text='S3 key cho ảnh bìa (JPG, PNG)', max_length=1024, null=True),
        ),
    ]
